activate:
	conda activate my_env


migration:
	python manage.py makemigrations

migrationApi:
	python manage.py makemigrations api


migrate:
	python manage.py migrate


serve:
	python manage.py runserver